### ISSUE TITLE
Images credits

### ISSUE THREAD

**Issue by le-jun** [Rage997/reMarkable_suspend#1]
[Galaxy](https://github.com/Rage997/reMarkable_suspend/blob/master/images/galaxy.png) looks like a black and white version of the cover of [Mystical Ennui](https://doonvorcannon.com/2021/03/26/mystical-ennui/) written by Doonvorcannon. Not sure if s/he’s the illustrator as well.
[Slave_1](https://github.com/Rage997/reMarkable_suspend/blob/master/images/slave_1.png) seems to be from [Urdicrates](https://www.reddit.com/user/Urdicrates/) who ["customized"](https://www.reddit.com/r/RemarkableTablet/comments/ky4mqs/finally_managed_to_customize_my_sleep_screen/) it.

**Comment by Rage997** [comment]
thanks! I've updated the readme with the appropriate credits.
